name: Bookshelf
version: ${project.version}
main: de.jasper557.bookshelf.Bookshelf
api-version: 1.16
authors: [ Jasper557 ]
description: When right-clicking on a bookshelf, a secret inventory opens up. In this inventory you can hide things.
